version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run tests
          command: npm test
